-- MySQL Script generated by MySQL Workbench
-- Mon Jan 27 14:05:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisesgepento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisesgepento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisesgepento` DEFAULT CHARACTER SET utf8 ;
USE `sisesgepento` ;

-- -----------------------------------------------------
-- Table `sisesgepento`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisesgepento`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `tipo` VARCHAR(50) NULL,
  `senha` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisesgepento`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisesgepento`.`aluno` (
  `cpf` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisesgepento`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisesgepento`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `ativo` TINYINT NULL,
  `data` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisesgepento`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisesgepento`.`disciplina` (
  `iddisciplina` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `ch` INT NULL,
  PRIMARY KEY (`iddisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisesgepento`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisesgepento`.`professor` (
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `disciplina_iddisciplina` INT NOT NULL,
  PRIMARY KEY (`cpf`, `disciplina_iddisciplina`),
  INDEX `fk_professor_disciplina1_idx` (`disciplina_iddisciplina` ASC),
  CONSTRAINT `fk_professor_disciplina1`
    FOREIGN KEY (`disciplina_iddisciplina`)
    REFERENCES `sisesgepento`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisesgepento`.`aluno_has_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisesgepento`.`aluno_has_curso` (
  `aluno_cpf` VARCHAR(50) NOT NULL,
  `curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`aluno_cpf`, `curso_idcurso`),
  INDEX `fk_aluno_has_curso_curso1_idx` (`curso_idcurso` ASC),
  INDEX `fk_aluno_has_curso_aluno_idx` (`aluno_cpf` ASC),
  CONSTRAINT `fk_aluno_has_curso_aluno`
    FOREIGN KEY (`aluno_cpf`)
    REFERENCES `sisesgepento`.`aluno` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_curso_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `sisesgepento`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisesgepento`.`curso_has_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisesgepento`.`curso_has_disciplina` (
  `curso_idcurso` INT NOT NULL,
  `disciplina_iddisciplina` INT NOT NULL,
  PRIMARY KEY (`curso_idcurso`, `disciplina_iddisciplina`),
  INDEX `fk_curso_has_disciplina_disciplina1_idx` (`disciplina_iddisciplina` ASC),
  INDEX `fk_curso_has_disciplina_curso1_idx` (`curso_idcurso` ASC),
  CONSTRAINT `fk_curso_has_disciplina_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `sisesgepento`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_iddisciplina`)
    REFERENCES `sisesgepento`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisesgepento`.`curso_has_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisesgepento`.`curso_has_professor` (
  `curso_idcurso` INT NOT NULL,
  `professor_cpf` INT NOT NULL,
  PRIMARY KEY (`curso_idcurso`, `professor_cpf`),
  INDEX `fk_curso_has_professor_professor1_idx` (`professor_cpf` ASC),
  INDEX `fk_curso_has_professor_curso1_idx` (`curso_idcurso` ASC),
  CONSTRAINT `fk_curso_has_professor_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `sisesgepento`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_has_professor_professor1`
    FOREIGN KEY (`professor_cpf`)
    REFERENCES `sisesgepento`.`professor` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
